version: '3'

volumes:
  postgres_data:

services:

  db:
    container_name: db-auth
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    container_name: redis-auth
    image: redis:6.0.9
    restart: on-failure

  auth_service:
    container_name: service-auth
    build: ./src
    env_file:
      - .env
    expose:
      - "8005"
    depends_on:
      - redis
      - db
    links:
      - db

  nginx:
    container_name: auth-nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config:/etc/nginx/conf.d:ro
    depends_on:
      - db
      - redis
      - auth_service
    ports:
      - "80:80"
